In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)

gfa_renames = {
    "largest_property_use_type_1": "largest_use_gfa_sqft",
    "_2nd_largest_property_use_1": "second_use_gfa_sqft",
    "_3rd_largest_property_use_1": "third_use_gfa_sqft",
}

df = pd.read_csv(
    "data/nyc_2024_data.csv.gz",
    dtype={"postal_code": str, **{c: str for c in gfa_renames}},
    na_values=["Not Available"],
    low_memory=False,
)

for col in gfa_renames:
    df[col] = pd.to_numeric(df[col].str.replace(",", ""), errors="coerce")
df = df.rename(columns=gfa_renames)

df.shape

(39090, 256)

In [2]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

summary = pd.DataFrame({
    "dtype": df.dtypes,
    "n_unique": df.nunique(),
    "n_missing": df.isna().sum(),
    "examples": [df[c].dropna().unique()[:5].tolist() for c in df.columns],
})
summary.sort_values("n_unique")

,dtype,n_unique,n_missing,examples
barracks_gross_floor_area,float64,0,39090,[]
kerosene_use_kbtu,float64,0,39090,[]
data_center_pue,float64,0,39090,[]
report_year,int64,1,0,[2024]
propane_use_kbtu,float64,1,39089,[92261.0]
data_center_pdu_output_meter,float64,1,38813,[0.0]
estimated_data_flag_fuel_3,str,1,38160,[No]
eligible_for_certification_for_report_ped_y_n_,str,1,0,[No]
national_median_energy_star,int64,1,0,[50]
institutional_property_y_n_,str,1,39089,[No]
estimated_data_flag_fuel,str,1,39084,[No]
wholesale_club_supercenter_1,str,1,39057,[100% Yes]
municipally_supplied_potable_3,float64,1,39089,[279.4]
data_center_national_median,float64,1,39050,[1.8]
report_generation_date,str,1,0,[2025-08-30T00:00:00.000]
aggregate_meter_s_district_steam_number_of_individual_meters_included,int64,1,0,[0]
aggregate_meter_s_natural_gas_number_of_individual_meters_included,int64,1,0,[0]
year_ending,str,1,0,[2024-12-31T00:00:00.000]
alert_energy_no_meters,str,2,0,"[Ok, Possible Issue]"
data_center_energy_estimates,str,2,38813,"[No, 100% Yes]"
fuel_oil_5_6_use_kbtu,float64,2,39088,"[2881350.1, 0.0]"
data_center_it_equipment,float64,2,38813,"[0.0, 106503.0]"
temporary_values,bool,2,0,"[False, True]"
hospital_general_medical_2,str,2,38974,"[100% Yes, No]"
data_center_pdu_input_meter,float64,2,38814,"[0.0, 21997.9]"
estimated_data_flag_2,str,2,38807,"[No, Yes]"
estimated_data_flag_diesel,str,2,38789,"[No, Yes]"
energy_star_certification_application_status,str,2,39083,"[Under Review, Escalated to Expert]"
third_party_certification,str,2,39076,"[LEED, Ecovadis]"
estimated_data_flag_fuel_1,str,2,32593,"[No, Yes]"
estimated_data_flag_fuel_2,str,2,37116,"[No, Yes]"
estimated_data_flag_district,str,2,37513,"[No, Yes]"
outdoor_water_use_all_water,float64,2,39088,"[4172.2, 279.4]"
estimated_data_flag_1,str,2,38617,"[No, Yes]"
data_quality_checker_run_,str,2,0,"[No, Yes]"
estimated_data_flag_natural,str,2,9533,"[No, Yes]"
estimated_data_flag,str,2,8361,"[Yes, No]"
multifamily_housing_government,str,2,25385,"[No, 100% Yes]"
alert_data_center_issue_with,str,2,0,"[Ok, Possible Issue]"
alert_property_has_no_uses,str,2,0,"[Ok, Possible Issue]"
fuel_oil_1_use_kbtu,float64,3,39087,"[3235100.0, 3083770.6, 0.0]"
alert_energy_meter_has_single,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
alert_energy_meter_has,str,3,0,"[Ok, Unable to Check (not enough data), Possible Issue]"
estimated_values_water,str,3,0,"[Unable to Check (not enough data), No, Yes]"
alert_energy_meter_has_gaps,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
alert_energy_meter_has_less,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
estimated_values_energy,str,3,0,"[Yes, No, Unable to Check (not enough data)]"
alert_water_meter_has_less,str,3,0,"[Unable to Check (not enough data), Ok, Possible Issue]"
alert_gross_floor_area_is,str,3,0,"[Ok, Unable to Check (not enough data), Possible Issue]"
percent_of_recs_retained,float64,3,38848,"[0.0, 100.0, 43.84]"
aggregate_meter_s_electric_number_of_individual_meters_included,int64,3,0,"[0, 15, 1]"
default_values,str,3,0,"[Yes, No, Unable to Check (not enough data)]"
construction_status,str,3,0,"[Existing, Test, Design]"
hospital_general_medical_10,float64,3,38867,"[100.0, 0.0, 90.0]"
district_hot_water_use_kbtu,float64,4,39085,"[21048000.6, 7277000.4, 0.0, 2824120.2]"
hospital_general_medical_9,float64,4,38867,"[100.0, 90.0, 0.0, 80.0]"
borough,str,5,1349,"[MANHATTAN, STATEN IS, BRONX, QUEENS, BROOKLYN]"
multifamily_housing_resident,str,5,26325,"[No specific resident population, Dedicated Senior/Independent Living, Dedicated Student, Other dedicated housing, Dedicated Special Accessibility Needs]"
metered_areas_water,str,5,15980,"[Whole Property, Tenant and/or common areas (partial energy or water loads), Another configuration, Common areas (all energy or water loads), Tenant areas (all energy or water loads)]"
data_center_it_energy,str,7,38813,"[UPS supports only IT Equipment (preferred) => Use UPS Output Meter, No IT Energy Configuration Selected (or using Estimates); UPS supports only IT Equipment (preferred) => Use UPS Output Meter, No IT Energy Configuration Selected (or using Estimates), UPS, including non-IT load less than 10% => Use UPS Output Meter, Facility Has No UPS Output Meter => Use PDU Input Meter]"
convention_center_gross_floor,float64,7,39081,"[45148.0, 8221.0, 36316.0, 80216.0, 11212.0]"
number_of_active_it_meters,int64,7,0,"[0, 3, 1, 2, 6]"
district_chilled_water_use,float64,8,39077,"[0.0, 12646607.8, 2595420.2, 40955994.1, 61198294.0]"
medical_office_number_of_1,float64,8,38046,"[0.0, 4.0, 1.0, 3.0, 2.0]"
data_center_cooling_equipment,str,9,39009,"[N, N+1, 2N, N; N+1, None of the Above]"
data_center_ups_system,str,9,39009,"[N, N+1, 2N, N+1; N+2, N; N+1]"
metered_areas_energy,str,11,8027,"[Whole Property, Another configuration, Common areas (all energy or water loads), Tenant Heating, Tenant Hot Water, Common Area Heating, Common Area Hot Water, Tenant areas (all energy or water loads)]"
annual_maximum_demand_mm,str,12,36450,"[07/2024, 06/2024, 09/2024, 01/2024, 04/2024]"
hospital_general_medical_4,float64,12,38867,"[12.0, 5.0, 1.0, 0.0, 2.0]"
energy_power_station_gross,float64,12,39056,"[1818.0, 63600.0, 311000.0, 41582.0, 35648.0]"
medical_office_percent_that_1,float64,12,38046,"[100.0, 90.0, 82.0, 67.95, 30.0]"
third_party_certification_2,str,13,39077,"[07/01/2011, 12/19/2011, 05/16/2016, 01/11/2022, 02/27/2012]"
medical_office_percent_that,float64,14,38046,"[100.0, 90.0, 68.0, 67.95, 30.0]"
wastewater_treatment_plant,float64,14,39076,"[1129933.0, 1546246.0, 509197.0, 686240.0, 1306271.0]"
third_party_certification_1,str,14,39076,"[07/01/2011, 12/19/2011, 05/16/2016, 01/11/2022, 02/27/2012]"
retail_store_number_of_walk,float64,17,36290,"[0.0, 2.0, 8.0, 5.0, 4.0]"
electric_distribution_utility,str,17,34,"[Consolidated Edison Co-NY Inc, Long Island Power Authority, Baltimore Gas & Electric Co, Public Service Elec & Gas Co, Virginia Electric & Power Co]"
occupancy,int64,21,0,"[55, 90, 95, 100, 60]"
multifamily_housing_percent_1,float64,22,12303,"[100.0, 90.0, 80.0, 88.23, 70.0]"
multifamily_housing_percent,float64,24,12303,"[100.0, 90.0, 80.0, 20.0, 0.0]"
data_center_it_source_energy,float64,27,39056,"[153421.3, 2831168.7, 9714806.5, 91369766.3, 8306533.5]"
data_center_it_site_energy,float64,27,39056,"[16059.0, 296345.7, 1016873.9, 9563909.6, 869466.3]"
wholesale_club_supercenter,float64,30,39057,"[125727.0, 25000.0, 130099.0, 144376.0, 159379.0]"
courthouse_gross_floor_area,float64,30,39054,"[19395.0, 20309.0, 830879.0, 291589.0, 182000.0]"
number_of_active_energy_meters_2,int64,32,0,"[0, 1, 4, 2, 3]"
data_center_ups_output_meter,float64,36,38838,"[16059.0, 721281.3, 0.0, 296345.7, 1841632.3]"
automobile_dealership_gross,float64,39,39049,"[226556.0, 75061.0, 137456.0, 32966.0, 58626.0]"
ambulatory_surgical_center,float64,41,39046,"[4671.0, 185697.0, 134228.0, 131110.0, 191215.0]"
adult_education_gross_floor,float64,42,39046,"[0.0, 107532.0, 49432.0, 37306.0, 915.0]"
national_median_reference,str,43,877,"[CBECS - Office & Bank/Financial, ASHE Survey, CBECS - Retail Store, CBECS - Laboratory, CBECS - Other]"
mailing_center_post_office,float64,44,39036,"[251613.0, 358.0, 41000.0, 2500.0, 1200.0]"
movie_theater_gross_floor,float64,45,39042,"[157925.0, 11739.0, 33617.0, 145044.0, 120051.0]"
financial_office_weekly,float64,45,38880,"[65.0, 90.0, 168.0, 80.0, 0.0]"
retail_store_number_of_open,float64,46,36290,"[0.0, 5.0, 51.0, 73.0, 6.0]"
council_district,float64,51,1354,"[4.0, 5.0, 10.0, 1.0, 2.0]"
office_percent_that_can_be_1,float64,55,35035,"[100.0, 99.73, 61.7, 0.0, 93.6]"
enclosed_mall_gross_floor,float64,59,39027,"[59924.0, 210353.0, 33624.0, 39612.0, 73266.0]"
community_board,float64,67,1354,"[105.0, 106.0, 108.0, 112.0, 101.0]"
_3rd_largest_property_use,str,69,35453,"[Food Service, Financial Office, Other - Entertainment/Public Assembly, Retail Store, College/University]"
office_percent_that_can_be,float64,71,35034,"[100.0, 99.05, 99.58, 42.83, 95.13]"
_2nd_largest_property_use,str,73,29718,"[Financial Office, Retail Store, Office, Restaurant, Laboratory]"
primary_property_type,str,77,44,"[Office, Financial Office, Hospital (General Medical & Surgical), Retail Store, Laboratory]"
electricity_use_generated_3,float64,78,38848,"[0.0, 70995.2, 58668.1, 20200.1, 25491.0]"
largest_property_use_type,str,78,44,"[Office, Financial Office, Hospital (General Medical & Surgical), Retail Store, Laboratory]"
primary_property_type_self,str,78,0,"[Office, Financial Office, Hospital (General Medical & Surgical), Retail Store, Laboratory]"
target_energy_star_score,float64,83,34196,"[75.0, 100.0, 69.0, 80.0, 93.0]"
refrigerated_warehouse_gross,float64,85,39000,"[5000.0, 40436.0, 0.0, 5005.0, 79551.0]"
medical_office_weekly,float64,85,38046,"[65.0, 43.0, 80.0, 55.0, 60.0]"
hotel_gym_fitness_center,float64,93,38870,"[4670.0, 1925.0, 9825.0, 0.0, 1951.0]"
number_of_buildings,int64,93,0,"[1, 5, 2, 4, 0]"
energy_star_score,float64,100,14752,"[69.0, 77.0, 63.0, 60.0, 12.0]"
avoided_emissions_offsite,float64,102,8923,"[0.0, 2618.75, 91.85, 1752.35, 4784.64]"
outpatient_rehabilitation,float64,103,38970,"[2202.0, 5018.0, 8450.0, 0.0, 5800.0]"
multifamily_housing_number_3,float64,106,25420,"[0.0, 36.0, 79.0, 64.0, 5.0]"
green_power_offsite_kwh,float64,107,8923,"[0.0, 5904211.0, 227724.0, 3950470.0, 11862460.0]"
avoided_emissions_onsite,float64,109,38848,"[0.0, 97.45, 63.36, 43.92, 86.77]"
hospital_general_medical_7,float64,110,38867,"[0.46295, 0.35045, 0.66635, 0.53187, 1.37501]"
green_power_onsite_kwh,float64,110,38848,"[0.0, 219698.8, 142838.9, 99015.0, 195603.0]"
hospital_general_medical_8,float64,114,38867,"[3.28857, 3.1592, 2.58778, 2.60003, 2.6]"
restaurant_weekly_operating,float64,120,37829,"[65.0, 60.0, 104.0, 80.0, 76.39]"
museum_gross_floor_area_ft,float64,127,38950,"[151844.0, 5777.0, 32618.0, 190723.0, 120000.0]"
laboratory_gross_floor_area,float64,139,38934,"[783461.0, 190111.0, 677983.0, 264771.0, 10972.0]"
reason_s_for_no_score,str,140,24338,"[Gross Floor Area is too small., More than 50% of the Gross Floor Area is not a single Property Type that is eligible for a 1-100 score (in your country)., Property Type cannot get a score as a campus., Weekly Operating Hours is outside the allowed range.; Number of Workers on Main Shift is too small., There is not 12 full months of meter data.; Meter(s) with gaps in meter entries.]"
urgent_care_clinic_other,float64,148,38906,"[2326.0, 18215.0, 10400.0, 3600.0, 1217.0]"
number_of_active_energy_meters,int64,151,0,"[5, 7, 19, 13, 3]"
food_sales_gross_floor_area,float64,152,38908,"[12943.0, 1373.0, 20000.0, 1512.0, 2622.0]"
number_of_active_energy_meters_1,int64,153,0,"[5, 7, 19, 13, 3]"
financial_office_number_of_1,float64,157,38880,"[25.57, 37.68, 316.0, 1105.64, 873.0]"
hospital_general_medical_5,float64,163,38867,"[0.00311, 0.00208, 0.00323, 0.0, 0.00385]"
performing_arts_gross_floor,float64,164,38908,"[174570.0, 145192.0, 44739.0, 9593.0, 99663.0]"
senior_living_community_living,float64,167,38849,"[1.49462, 0.92034, 1.23295, 0.80128, 1.88588]"
hospital_general_medical_6,float64,169,38867,"[1786.0, 843.0, 206.0, 70.0, 357.0]"
financial_office_number_of,float64,170,38880,"[22.23, 32.77, 1280.0, 961.42, 2617.0]"
supermarket_grocery_number,float64,173,38592,"[5.0, 20.0, 0.15, 13.0, 8.0]"
hospital_general_medical_3,float64,177,38867,"[2661.95, 2050.6, 213.31, 90.81, 179.1]"
diesel_2_use_kbtu,float64,180,38842,"[220800.0, 521502.2, 1110348.0, 138000.0, 7169.1]"
hospital_general_medical,float64,182,38867,"[12687.0, 7599.4, 800.0, 342.19, 675.05]"
electricity_use_generated,float64,186,38848,"[230007.0, 768705.0, 219698.8, 142838.9, 99015.0]"
electricity_use_generated_1,float64,186,38848,"[784783.9, 2622821.5, 749612.3, 487366.3, 337839.1]"
percent_of_electricity_that,float64,188,8999,"[0.0, 58.27, 17.62, 34.86, 52.71]"
percent_of_total_electricity,float64,195,38849,"[36.97, 39.54, 32.82, 36.51, 13.05]"
financial_office_gross_floor,float64,197,38880,"[11116.0, 16383.0, 368732.0, 480712.0, 716348.2]"
year_built,int64,199,0,"[1982, 1956, 1989, 1961, 1999]"
supermarket_grocery_number_1,float64,204,38592,"[40.0, 285.0, 0.58, 50.0, 4.0]"
electricity_use_generated_2,float64,207,38848,"[230007.0, 768705.0, 290694.0, 201507.0, 119215.1]"
avoided_emissions_onsite_1,float64,207,8922,"[0.0, 2618.75, 91.85, 1752.35, 4784.64]"
natural_gas_weather_normalized_1,float64,208,10349,"[0.0, 0.2, 3.0, 5.4, 1.4]"
parking_partially_enclosed,float64,208,35439,"[0.0, 39590.0, 182360.0, 40310.0, 199497.0]"
distribution_center_gross,float64,209,38854,"[61284.0, 151350.0, 214000.0, 175559.0, 8528.0]"
social_meeting_hall_gross,float64,211,38833,"[41501.0, 59000.0, 12084.0, 13909.0, 69019.0]"
green_power_onsite_and_offsite,float64,213,8922,"[0.0, 5904211.0, 227724.0, 3950470.0, 11862460.0]"
hospital_general_medical_1,float64,213,38867,"[3857905.0, 2405480.0, 309145.0, 131610.0, 259635.0]"
data_quality_checker_date_run,str,218,27086,"[2025-06-10, 2024-12-13, 2025-08-20, 2025-04-21, 2025-03-06]"
senior_living_community_gross,float64,222,38849,"[93000.0, 107569.0, 63263.0, 124800.0, 247884.0]"
strip_mall_gross_floor_area,float64,225,38769,"[9100.0, 14000.0, 56315.0, 75990.0, 7805.0]"
nta2020,str,230,1354,"[MN0502, MN0603, MN0604, MN0801, MN1292]"
leed_us_project_id,float64,243,38846,"[1000074571.0, 1000098026.0, 1000065321.0, 1000053782.0, 1000112314.0]"
data_center_gross_floor_area,float64,249,38813,"[1391.8, 7624.0, 0.0, 3156.0, 13000.0]"
municipally_supplied_potable,float64,251,38834,"[12545.7, 23245.0, 7721.7, 9541.1, 31786.7]"
city,str,272,0,"[Manhattan, New York, New York City, STATEN ISLAND, BRONX]"
residence_hall_dormitory,float64,301,38715,"[15096.0, 79756.0, 98118.0, 76264.0, 69078.0]"
other_gross_floor_area_ft,float64,311,38726,"[396315.0, 8270.0, 19224.3, 87314.0, 9000.0]"
energy_star_certification_1,str,317,38602,"[09/09/2020, 07/02/2018, 05/02/2018, 03/22/2011, 07/19/2011]"
bank_branch_gross_floor_area,float64,324,38711,"[0.0, 3023.0, 4239.0, 8617.0, 7238.0]"
food_service_gross_floor,float64,337,38698,"[9494.0, 18924.0, 13240.0, 1250.0, 14000.0]"
worship_facility_gross_floor,float64,345,38653,"[3586.0, 2900.0, 3879.0, 20239.0, 109382.0]"
postal_code,str,379,0,"[10036, 10017, 10032, 10021, 10034]"
pre_school_daycare_gross,float64,391,38625,"[15120.0, 6120.0, 5100.0, 10000.0, 3440.0]"
self_storage_facility_gross,float64,392,38687,"[6414.0, 213331.0, 141935.0, 80743.0, 177921.0]"
supermarket_grocery_gross,float64,396,38592,"[60000.0, 112687.0, 585.0, 50942.0, 4290.0]"
multifamily_housing_number_2,float64,396,25663,"[105.0, 20.0, 0.0, 251.0, 226.0]"
multifamily_housing_number_6,float64,421,12303,"[0.0, 15.0, 25.0, 13.0, 45.0]"
college_university_gross,float64,426,38637,"[454658.0, 197505.0, 108124.0, 194563.0, 188491.0]"
medical_office_number_of_2,float64,426,38046,"[11.53, 13.0, 340.0, 107.0, 30.0]"
parking_open_parking_lot,float64,446,35439,"[0.0, 79196.0, 91262.0, 5246.0, 198170.0]"
manufacturing_industrial,float64,446,38556,"[168571.0, 76000.0, 61273.0, 21118.0, 67749.0]"
energy_star_certification,str,448,38603,"[2001 (78), 2002 (83), 2003 (88), 2005 (91), 2006 (81), 2008 (75), 2010 (82), 2015 (84), 2017 (79), 2020 (80), 2001 (83), 2008 (77), 2010 (82), 2015 (83), 2017 (78), 2018 (80), 2001 (75), 2002 (76), 2003 (75), 2005 (77), 2006 (85), 2008 (86), 2010 (83), 2015 (86), 2016 (91), 2018 (87), 2001 (76), 2003 (78), 2005 (85), 2006 (78), 2008 (91), 2010 (75), 2015 (76), 2017 (79), 2018 (83), 2001 (75), 2002 (76), 2003 (76), 2005 (78), 2006 (78), 2008 (83), 2010 (75)]"
fitness_center_health_club,float64,498,38507,"[75760.0, 1538.0, 34000.0, 5760.0, 6000.0]"
restaurant_worker_density,float64,508,37845,"[2.2011, 2.19984, 2.2, 2.20034, 0.14164]"
medical_office_number_of,float64,515,38046,"[10.48, 13.0, 350.0, 122.0, 35.0]"
non_refrigerated_warehouse,float64,521,38476,"[5000.0, 17724.0, 440700.0, 3261.0, 16566.0]"
office_weekly_operating_hours,float64,586,35034,"[65.0, 76.0, 98.0, 39.18, 66.18]"
electricity_weather_normalized_1,float64,682,9104,"[13.0, 8.6, 11.0, 12.1, 17.3]"
hotel_gross_floor_area_ft,float64,729,38309,"[296302.0, 882210.0, 427877.0, 208520.0, 130250.0]"
multifamily_housing_number_4,float64,754,12303,"[0.0, 105.0, 340.0, 921.0, 481.0]"
medical_office_gross_floor,float64,810,38046,"[5241.0, 5184.0, 107393.0, 42312.0, 11996.0]"
fuel_oil_4_use_kbtu,float64,848,38055,"[8103525.8, 5827298.1, 3212438.0, 6732994.7, 4323848.3]"
restaurant_gross_floor_area,float64,884,37829,"[3262.0, 18515.0, 34269.0, 6449.0, 10390.0]"
percent_electricity,float64,1002,9428,"[81.3, 33.7, 62.6, 49.8, 74.2]"
district_steam_use_kbtu,float64,1220,37624,"[6620658.4, 22263884.8, 11904586.2, 14319701.5, 7638053.8]"
ct2020,float64,1374,1354,"[119.0, 88.0, 125.0, 90.0, 116.0]"
direct_ghg_emissions_intensity,float64,1469,10036,"[0.04, 0.07, 0.24, 0.84, 15.83]"
k_12_school_gross_floor_area,float64,1529,36944,"[171725.0, 124900.0, 175325.0, 111600.0, 188575.0]"
annual_maximum_demand_kw,float64,1690,36450,"[2403.8, 278.9, 258.6, 291.2, 138.2]"
office_number_of_workers,float64,1703,35034,"[2268.78, 332.0, 344.08, 422.0, 893.0]"
indirect_location_based_ghg_1,float64,1729,8951,"[5.77, 7.25, 5.67, 7.16, 7.12]"
national_median_site_eui,float64,1743,940,"[46.6, 114.4, 89.3, 99.1, 91.0]"
office_number_of_computers,float64,1747,35034,"[3883.2, 1670.0, 299.2, 1810.0, 3008.0]"
multifamily_housing_total,float64,1812,12303,"[716.78, 105.0, 340.0, 921.0, 481.0]"
parking_completely_enclosed,float64,1952,35439,"[211980.0, 0.0, 84718.0, 141378.0, 68700.0]"
parent_property_id,str,2003,0,"[Not Applicable: Standalone Property, 28400, 28402, 48489992, 33999525]"
parent_property_name,str,2003,0,"[Not Applicable: Standalone Property, NYP Columbia (West Campus), NYP Cornell (East Campus), ABC Building, Brewster LLC (Parent)]"
parking_gross_floor_area,float64,2088,35439,"[211980.0, 0.0, 84718.0, 141378.0, 68700.0]"
retail_store_gross_floor,float64,2105,36289,"[4840.0, 23310.0, 6021.0, 61047.0, 12885.0]"
national_median_source_eui,float64,2248,940,"[116.4, 199.1, 196.3, 197.1, 214.5]"
total_location_based_ghg_1,float64,2315,8521,"[5.81, 7.25, 5.75, 7.41, 7.96]"
property_gfa_calculated_2,float64,2326,35439,"[211980.0, 79196.0, 91262.0, 84718.0, 141378.0]"
annual_maximum_demand_meter,str,2409,36450,"[Con Ed 494021425800009 (ELECTRIC) (5704952), 0200140E (8052689), 0200146E (8052691), 0200168E (8080069), 0200184E (8080071)]"
third_use_gfa_sqft,float64,2468,35453,"[9494.0, 16383.0, 32668.0, 6021.0, 61047.0]"
office_worker_density_number,float64,2704,35046,"[3.39333, 0.98462, 2.3, 1.20918, 0.87489]"
site_eui_kbtu_ft,float64,2713,8513,"[54.9, 87.6, 59.5, 82.4, 79.7]"
weather_normalized_site_eui,float64,2719,9757,"[55.9, 90.3, 62.1, 84.7, 81.0]"
multifamily_housing_number,float64,2720,12303,"[836.24, 264.0, 600.0, 1700.0, 579.0]"
fuel_oil_2_use_kbtu,float64,3245,34261,"[8214759.8, 8033460.0, 1656000.0, 11065585.1, 483138.1]"
office_gross_floor_area_ft,float64,3347,35032,"[668602.0, 337187.0, 149601.0, 348996.0, 1020704.0]"
weather_normalized_source,float64,3876,9757,"[138.0, 155.4, 134.2, 167.3, 189.3]"
source_eui_kbtu_ft,float64,3885,8513,"[137.2, 152.4, 130.9, 163.9, 187.9]"
multifamily_housing_number_5,float64,4797,12313,"[0.0, 0.34386, 0.90498, 1.07861, 1.17459]"
second_use_gfa_sqft,float64,5434,29718,"[11116.0, 23310.0, 149601.0, 34269.0, 480712.0]"
property_notes,str,9460,26598,"[1-00997-0029, 1-01315-0001, 1-00999-0019, 1-01319-0047, 1-00995-0005]"
multifamily_housing_number_7,float64,11704,12313,"[0.0, 0.29101, 0.1909, 0.24649, 0.32459]"
indoor_water_use_all_water,float64,13760,20708,"[5235.6, 18617.9, 259.3, 4842.2, 27724.4]"
municipally_supplied_potable_2,float64,13761,20707,"[5235.6, 18617.9, 259.3, 4842.2, 27724.4]"
municipally_supplied_potable_1,float64,13953,20472,"[5235.6, 18617.9, 259.3, 12545.7, 4842.2]"
water_use_all_water_sources,float64,13953,20470,"[5235.6, 18617.9, 259.3, 12545.7, 4842.2]"

In [3]:
#Dropping columns that have the same value in every row or no values at all
constant_cols = df.columns[df.nunique(dropna=False) <= 1]
df = df.drop(columns=constant_cols)
print(f"Dropped {len(constant_cols)} columns: {list(constant_cols)}")

Dropped 10 columns: ['report_year', 'year_ending', 'national_median_energy_star', 'eligible_for_certification_for_report_ped_y_n_', 'kerosene_use_kbtu', 'data_center_pue', 'barracks_gross_floor_area', 'aggregate_meter_s_natural_gas_number_of_individual_meters_included', 'aggregate_meter_s_district_steam_number_of_individual_meters_included', 'report_generation_date']

In [4]:
#Dropping columns where at least 98% of the rows are empty
missing_share = df.isna().mean()
mostly_empty = missing_share[missing_share > 0.98].index
print(f"Dropping {len(mostly_empty)} columns: {list(mostly_empty)}")
df = df.drop(columns=mostly_empty)

Dropping 96 columns: ['energy_star_certification', 'energy_star_certification_1', 'energy_star_certification_application_status', 'fuel_oil_1_use_kbtu', 'fuel_oil_5_6_use_kbtu', 'diesel_2_use_kbtu', 'propane_use_kbtu', 'district_hot_water_use_kbtu', 'district_chilled_water_use', 'electricity_use_generated', 'electricity_use_generated_1', 'electricity_use_generated_2', 'electricity_use_generated_3', 'green_power_onsite_kwh', 'avoided_emissions_onsite', 'percent_of_recs_retained', 'percent_of_total_electricity', 'leed_us_project_id', 'estimated_data_flag_1', 'estimated_data_flag_fuel', 'estimated_data_flag_diesel', 'estimated_data_flag_2', 'data_center_ups_output_meter', 'data_center_pdu_input_meter', 'data_center_pdu_output_meter', 'data_center_it_equipment', 'data_center_it_site_energy', 'data_center_it_source_energy', 'data_center_national_median', 'data_center_gross_floor_area', 'data_center_ups_system', 'data_center_it_energy', 'data_center_energy_estimates', 'data_center_cooling_equipment', 'adult_education_gross_floor', 'ambulatory_surgical_center', 'automobile_dealership_gross', 'bank_branch_gross_floor_area', 'college_university_gross', 'convention_center_gross_floor', 'courthouse_gross_floor_area', 'distribution_center_gross', 'enclosed_mall_gross_floor', 'energy_power_station_gross', 'financial_office_gross_floor', 'financial_office_number_of', 'financial_office_weekly', 'financial_office_number_of_1', 'fitness_center_health_club', 'food_sales_gross_floor_area', 'food_service_gross_floor', 'hospital_general_medical', 'hospital_general_medical_1', 'hospital_general_medical_2', 'hospital_general_medical_3', 'hospital_general_medical_4', 'hospital_general_medical_5', 'hospital_general_medical_6', 'hospital_general_medical_7', 'hospital_general_medical_8', 'hospital_general_medical_9', 'hospital_general_medical_10', 'outpatient_rehabilitation', 'urgent_care_clinic_other', 'hotel_gross_floor_area_ft', 'hotel_gym_fitness_center', 'pre_school_daycare_gross', 'laboratory_gross_floor_area', 'mailing_center_post_office', 'movie_theater_gross_floor', 'manufacturing_industrial', 'institutional_property_y_n_', 'residence_hall_dormitory', 'refrigerated_warehouse_gross', 'non_refrigerated_warehouse', 'other_gross_floor_area_ft', 'museum_gross_floor_area_ft', 'performing_arts_gross_floor', 'self_storage_facility_gross', 'senior_living_community_gross', 'senior_living_community_living', 'social_meeting_hall_gross', 'supermarket_grocery_gross', 'supermarket_grocery_number', 'supermarket_grocery_number_1', 'wholesale_club_supercenter', 'wholesale_club_supercenter_1', 'wastewater_treatment_plant', 'worship_facility_gross_floor', 'strip_mall_gross_floor_area', 'outdoor_water_use_all_water', 'municipally_supplied_potable', 'municipally_supplied_potable_3', 'third_party_certification', 'third_party_certification_1', 'third_party_certification_2']

In [5]:
#Dropping most of the identifier columns, keeping one as index
df = df.set_index("property_id")
df = df.drop(columns=["property_name", "nyc_building_identification", "address_1"])

In [6]:
#Checking for duplicate columns
from itertools import combinations

def find_duplicate_pairs(df, threshold=0.99, min_overlap=100):
    results = []
    for a, b in combinations(df.columns, 2):
        both = df[a].notna() & df[b].notna()
        n = both.sum()
        if n < min_overlap:
            continue
        x, y = df.loc[both, a], df.loc[both, b]
        numeric = (pd.api.types.is_numeric_dtype(x) and pd.api.types.is_numeric_dtype(y)
                   and not pd.api.types.is_bool_dtype(x) and not pd.api.types.is_bool_dtype(y))
        if numeric:
            match = np.isclose(x, y, rtol=0.001).mean()
            corr = x.corr(y, method="spearman") if x.std() > 0 and y.std() > 0 else np.nan
        else:
            match = (x.astype(str) == y.astype(str)).mean()
            corr = np.nan
        if match >= threshold or (not np.isnan(corr) and abs(corr) >= threshold):
            results.append({
                "col_a": a, "col_b": b, "overlap": n,
                "match": round(match, 4),
                "corr": round(corr, 4) if not np.isnan(corr) else None,
                "missing_a": df[a].isna().sum(), "missing_b": df[b].isna().sum(),
            })
    return pd.DataFrame(results).sort_values(["match", "corr"], ascending=False)

dupes = find_duplicate_pairs(df)
dupes

,col_a,col_b,overlap,match,corr,missing_a,missing_b
58,estimated_data_flag_fuel_1,estimated_data_flag_fuel_3,643,1.0000,NaN,32593,38160
59,estimated_data_flag_fuel_2,estimated_data_flag_fuel_3,325,1.0000,NaN,37116,38160
72,indoor_water_use_all_water,municipally_supplied_potable_2,18382,0.9998,1.0000,20708,20707
69,water_use_all_water_sources,municipally_supplied_potable_1,18616,0.9996,1.0000,20470,20472
73,municipally_supplied_potable_1,municipally_supplied_potable_2,18375,0.9991,0.9999,20472,20707
68,water_use_all_water_sources,indoor_water_use_all_water,18373,0.9989,0.9999,20470,20708
71,indoor_water_use_all_water,municipally_supplied_potable_1,18374,0.9989,0.9999,20708,20472
56,alert_property_has_no_uses,alert_gross_floor_area_is,39090,0.9988,NaN,0,0
70,water_use_all_water_sources,municipally_supplied_potable_2,18373,0.9987,0.9999,20470,20707
6,metered_areas_energy,metered_areas_water,22961,0.9985,NaN,8027,15980
75,number_of_active_it_meters,aggregate_meter_s_electric_number_of_individual_meters_included,39090,0.9984,-0.0003,0,0
55,alert_property_has_no_uses,alert_data_center_issue_with,39090,0.9979,NaN,0,0
57,alert_data_center_issue_with,alert_gross_floor_area_is,39090,0.9974,NaN,0,0
45,avoided_emissions_offsite,aggregate_meter_s_electric_number_of_individual_meters_included,30167,0.9965,-0.0005,8923,0
32,green_power_offsite_kwh,avoided_emissions_offsite,30167,0.9964,0.9861,8923,8923
31,green_power_offsite_kwh,green_power_onsite_and_offsite,30167,0.9964,0.7122,8923,8922
42,avoided_emissions_offsite,avoided_emissions_onsite_1,30167,0.9964,0.7073,8923,8922
36,green_power_offsite_kwh,aggregate_meter_s_electric_number_of_individual_meters_included,30167,0.9964,-0.0005,8923,0
52,alert_energy_no_meters,alert_property_has_no_uses,39090,0.9962,NaN,0,0
54,alert_energy_no_meters,alert_gross_floor_area_is,39090,0.9956,NaN,0,0
2,largest_use_gfa_sqft,multifamily_housing_gross,26779,0.9953,0.9974,44,12301
53,alert_energy_no_meters,alert_data_center_issue_with,39090,0.9953,NaN,0,0
44,avoided_emissions_offsite,number_of_active_it_meters,30167,0.9947,0.0733,8923,0
35,green_power_offsite_kwh,number_of_active_it_meters,30167,0.9946,0.0722,8923,0
60,medical_office_percent_that,medical_office_percent_that_1,1044,0.9933,0.9385,38046,38046
46,avoided_emissions_onsite_1,percent_of_electricity_that,30091,0.9931,1.0000,8922,8999
43,avoided_emissions_offsite,percent_of_electricity_that,30091,0.9931,0.7070,8923,8999
50,percent_of_electricity_that,aggregate_meter_s_electric_number_of_individual_meters_included,30091,0.9930,-0.0007,8999,0
23,electricity_use_grid_purchase,electricity_use_grid_purchase_3,30160,0.9929,0.9993,8928,8923
38,green_power_onsite_and_offsite,avoided_emissions_onsite_1,30168,0.9929,0.9930,8922,8922
39,green_power_onsite_and_offsite,percent_of_electricity_that,30091,0.9929,0.9930,8922,8999
37,green_power_onsite_and_offsite,avoided_emissions_offsite,30167,0.9929,0.7024,8922,8923
33,green_power_offsite_kwh,avoided_emissions_onsite_1,30167,0.9929,0.6974,8923,8922
34,green_power_offsite_kwh,percent_of_electricity_that,30091,0.9929,0.6971,8923,8999
48,avoided_emissions_onsite_1,aggregate_meter_s_electric_number_of_individual_meters_included,30168,0.9929,-0.0007,8922,0
25,electricity_use_grid_purchase_1,electricity_use_grid_purchase_2,30160,0.9928,0.9993,8928,8923
41,green_power_onsite_and_offsite,aggregate_meter_s_electric_number_of_individual_meters_included,30168,0.9928,-0.0007,8922,0
49,percent_of_electricity_that,number_of_active_it_meters,30091,0.9912,0.0501,8999,0
47,avoided_emissions_onsite_1,number_of_active_it_meters,30168,0.9912,0.0500,8922,0
40,green_power_onsite_and_offsite,number_of_active_it_meters,30168,0.9911,0.0496,8922,0
1,primary_property_type,largest_property_use_type,39046,0.9908,NaN,44,44
51,alert_energy_meter_has_gaps,alert_energy_meter_has,39090,0.9907,NaN,0,0
0,primary_property_type_self,primary_property_type,39046,0.9903,NaN,0,44
66,property_gfa_self_reported,property_gfa_calculated_1,39055,0.9809,0.9987,0,35
74,number_of_active_energy_meters,number_of_active_energy_meters_1,39090,0.9779,0.9939,0,0
65,property_gfa_self_reported,property_gfa_calculated,39055,0.9176,0.9971,0,35
67,property_gfa_calculated,property_gfa_calculated_1,39055,0.9156,0.9974,35,35
63,multifamily_housing_gross,property_gfa_calculated_1,26788,0.8312,0.9932,12301,35
61,multifamily_housing_gross,property_gfa_self_reported,26789,0.8223,0.9927,12301,0
5,largest_use_gfa_sqft,property_gfa_calculated_1,39046,0.8139,0.9919,44,35
64,multifamily_housing_number_4,multifamily_housing_number_5,26777,0.8071,0.9926,12303,12313
3,largest_use_gfa_sqft,property_gfa_self_reported,39046,0.8021,0.9911,44,0
62,multifamily_housing_gross,property_gfa_calculated,26788,0.7763,0.9919,12301,35
4,largest_use_gfa_sqft,property_gfa_calculated,39046,0.7682,0.9904,44,35
15,natural_gas_weather_normalized,natural_gas_use_therms_,28753,0.2210,0.9996,10337,10201
11,electricity_weather_normalized,electricity_use_grid_purchase_2,29998,0.2121,0.9998,9092,8923
10,electricity_weather_normalized,electricity_use_grid_purchase_1,29991,0.2101,0.9991,9092,8928
7,site_eui_kbtu_ft,weather_normalized_site_eui,29280,0.0928,0.9986,8513,9757
8,site_energy_use_kbtu,weather_normalized_site_energy,29298,0.0891,0.9996,8495,9739
16,source_eui_kbtu_ft,weather_normalized_source,29280,0.0855,0.9989,8513,9757
17,source_energy_use_kbtu,weather_normalized_source_1,29298,0.0842,0.9998,8495,9739
14,natural_gas_weather_normalized,natural_gas_use_kbtu,28753,0.0226,0.9996,10337,10201
20,natural_gas_use_kbtu,natural_gas_use_therms_,28889,0.0225,1.0000,10201,10201
21,electricity_use_grid_purchase,electricity_use_grid_purchase_1,30162,0.0025,1.0000,8928,8928
28,electricity_use_grid_purchase_2,electricity_use_grid_purchase_3,30167,0.0025,1.0000,8923,8923
22,electricity_use_grid_purchase,electricity_use_grid_purchase_2,30160,0.0025,0.9993,8928,8923
26,electricity_use_grid_purchase_1,electricity_use_grid_purchase_3,30160,0.0025,0.9993,8928,8923
29,electricity_use_grid_purchase_2,indirect_location_based_ghg,30149,0.0025,0.9947,8923,8939
30,electricity_use_grid_purchase_3,indirect_location_based_ghg,30149,0.0025,0.9947,8923,8939
24,electricity_use_grid_purchase,indirect_location_based_ghg,30142,0.0025,0.9945,8928,8939
27,electricity_use_grid_purchase_1,indirect_location_based_ghg,30142,0.0025,0.9945,8928,8939
12,electricity_weather_normalized,electricity_use_grid_purchase_3,29998,0.0020,0.9998,9092,8923
9,electricity_weather_normalized,electricity_use_grid_purchase,29991,0.0020,0.9991,9092,8928
13,electricity_weather_normalized,indirect_location_based_ghg,29980,0.0020,0.9946,9092,8939
18,source_energy_use_kbtu,total_location_based_ghg,30587,0.0020,0.9927,8495,8503
19,weather_normalized_source_1,total_location_based_ghg,29294,0.0016,0.9930,9739,8503

In [7]:
#Dropping duplicates
df = df.drop(columns=[
    "indoor_water_use_all_water", "municipally_supplied_potable_1", "municipally_supplied_potable_2",
    "electricity_use_grid_purchase_1", "electricity_use_grid_purchase_2", "electricity_use_grid_purchase_3",
    "natural_gas_use_therms_",
    "primary_property_type", "largest_property_use_type",
    "property_gfa_calculated", "property_gfa_calculated_1",
    "estimated_data_flag_fuel_3",
    "weather_normalized_site_eui", "weather_normalized_site_energy",
    "weather_normalized_source", "weather_normalized_source_1",
    "natural_gas_weather_normalized", "electricity_weather_normalized",
    "number_of_active_energy_meters_1",
])

In [9]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

summary = pd.DataFrame({
    "dtype": df.dtypes,
    "n_unique": df.nunique(),
    "n_missing": df.isna().sum(),
    "examples": [df[c].dropna().unique()[:5].tolist() for c in df.columns],
})
summary.sort_values("n_unique")

,dtype,n_unique,n_missing,examples
alert_data_center_issue_with,str,2,0,"[Ok, Possible Issue]"
multifamily_housing_government,str,2,25385,"[No, 100% Yes]"
estimated_data_flag_fuel_2,str,2,37116,"[No, Yes]"
estimated_data_flag_fuel_1,str,2,32593,"[No, Yes]"
estimated_data_flag_district,str,2,37513,"[No, Yes]"
estimated_data_flag_natural,str,2,9533,"[No, Yes]"
estimated_data_flag,str,2,8361,"[Yes, No]"
temporary_values,bool,2,0,"[False, True]"
alert_energy_no_meters,str,2,0,"[Ok, Possible Issue]"
alert_property_has_no_uses,str,2,0,"[Ok, Possible Issue]"
data_quality_checker_run_,str,2,0,"[No, Yes]"
estimated_values_energy,str,3,0,"[Yes, No, Unable to Check (not enough data)]"
alert_water_meter_has_less,str,3,0,"[Unable to Check (not enough data), Ok, Possible Issue]"
default_values,str,3,0,"[Yes, No, Unable to Check (not enough data)]"
alert_energy_meter_has_less,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
alert_energy_meter_has_gaps,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
alert_energy_meter_has,str,3,0,"[Ok, Unable to Check (not enough data), Possible Issue]"
alert_energy_meter_has_single,str,3,0,"[Ok, Possible Issue, Unable to Check (not enough data)]"
estimated_values_water,str,3,0,"[Unable to Check (not enough data), No, Yes]"
alert_gross_floor_area_is,str,3,0,"[Ok, Unable to Check (not enough data), Possible Issue]"
aggregate_meter_s_electric_number_of_individual_meters_included,int64,3,0,"[0, 15, 1]"
construction_status,str,3,0,"[Existing, Test, Design]"
multifamily_housing_resident,str,5,26325,"[No specific resident population, Dedicated Senior/Independent Living, Dedicated Student, Other dedicated housing, Dedicated Special Accessibility Needs]"
borough,str,5,1349,"[MANHATTAN, STATEN IS, BRONX, QUEENS, BROOKLYN]"
metered_areas_water,str,5,15980,"[Whole Property, Tenant and/or common areas (partial energy or water loads), Another configuration, Common areas (all energy or water loads), Tenant areas (all energy or water loads)]"
number_of_active_it_meters,int64,7,0,"[0, 3, 1, 2, 6]"
medical_office_number_of_1,float64,8,38046,"[0.0, 4.0, 1.0, 3.0, 2.0]"
metered_areas_energy,str,11,8027,"[Whole Property, Another configuration, Common areas (all energy or water loads), Tenant Heating, Tenant Hot Water, Common Area Heating, Common Area Hot Water, Tenant areas (all energy or water loads)]"
medical_office_percent_that_1,float64,12,38046,"[100.0, 90.0, 82.0, 67.95, 30.0]"
annual_maximum_demand_mm,str,12,36450,"[07/2024, 06/2024, 09/2024, 01/2024, 04/2024]"
medical_office_percent_that,float64,14,38046,"[100.0, 90.0, 68.0, 67.95, 30.0]"
electric_distribution_utility,str,17,34,"[Consolidated Edison Co-NY Inc, Long Island Power Authority, Baltimore Gas & Electric Co, Public Service Elec & Gas Co, Virginia Electric & Power Co]"
retail_store_number_of_walk,float64,17,36290,"[0.0, 2.0, 8.0, 5.0, 4.0]"
occupancy,int64,21,0,"[55, 90, 95, 100, 60]"
multifamily_housing_percent_1,float64,22,12303,"[100.0, 90.0, 80.0, 88.23, 70.0]"
multifamily_housing_percent,float64,24,12303,"[100.0, 90.0, 80.0, 20.0, 0.0]"
number_of_active_energy_meters_2,int64,32,0,"[0, 1, 4, 2, 3]"
national_median_reference,str,43,877,"[CBECS - Office & Bank/Financial, ASHE Survey, CBECS - Retail Store, CBECS - Laboratory, CBECS - Other]"
retail_store_number_of_open,float64,46,36290,"[0.0, 5.0, 51.0, 73.0, 6.0]"
council_district,float64,51,1354,"[4.0, 5.0, 10.0, 1.0, 2.0]"
office_percent_that_can_be_1,float64,55,35035,"[100.0, 99.73, 61.7, 0.0, 93.6]"
community_board,float64,67,1354,"[105.0, 106.0, 108.0, 112.0, 101.0]"
_3rd_largest_property_use,str,69,35453,"[Food Service, Financial Office, Other - Entertainment/Public Assembly, Retail Store, College/University]"
office_percent_that_can_be,float64,71,35034,"[100.0, 99.05, 99.58, 42.83, 95.13]"
_2nd_largest_property_use,str,73,29718,"[Financial Office, Retail Store, Office, Restaurant, Laboratory]"
primary_property_type_self,str,78,0,"[Office, Financial Office, Hospital (General Medical & Surgical), Retail Store, Laboratory]"
target_energy_star_score,float64,83,34196,"[75.0, 100.0, 69.0, 80.0, 93.0]"
medical_office_weekly,float64,85,38046,"[65.0, 43.0, 80.0, 55.0, 60.0]"
number_of_buildings,int64,93,0,"[1, 5, 2, 4, 0]"
energy_star_score,float64,100,14752,"[69.0, 77.0, 63.0, 60.0, 12.0]"
avoided_emissions_offsite,float64,102,8923,"[0.0, 2618.75, 91.85, 1752.35, 4784.64]"
multifamily_housing_number_3,float64,106,25420,"[0.0, 36.0, 79.0, 64.0, 5.0]"
green_power_offsite_kwh,float64,107,8923,"[0.0, 5904211.0, 227724.0, 3950470.0, 11862460.0]"
restaurant_weekly_operating,float64,120,37829,"[65.0, 60.0, 104.0, 80.0, 76.39]"
reason_s_for_no_score,str,140,24338,"[Gross Floor Area is too small., More than 50% of the Gross Floor Area is not a single Property Type that is eligible for a 1-100 score (in your country)., Property Type cannot get a score as a campus., Weekly Operating Hours is outside the allowed range.; Number of Workers on Main Shift is too small., There is not 12 full months of meter data.; Meter(s) with gaps in meter entries.]"
number_of_active_energy_meters,int64,151,0,"[5, 7, 19, 13, 3]"
percent_of_electricity_that,float64,188,8999,"[0.0, 58.27, 17.62, 34.86, 52.71]"
year_built,int64,199,0,"[1982, 1956, 1989, 1961, 1999]"
avoided_emissions_onsite_1,float64,207,8922,"[0.0, 2618.75, 91.85, 1752.35, 4784.64]"
natural_gas_weather_normalized_1,float64,208,10349,"[0.0, 0.2, 3.0, 5.4, 1.4]"
parking_partially_enclosed,float64,208,35439,"[0.0, 39590.0, 182360.0, 40310.0, 199497.0]"
green_power_onsite_and_offsite,float64,213,8922,"[0.0, 5904211.0, 227724.0, 3950470.0, 11862460.0]"
data_quality_checker_date_run,str,218,27086,"[2025-06-10, 2024-12-13, 2025-08-20, 2025-04-21, 2025-03-06]"
nta2020,str,230,1354,"[MN0502, MN0603, MN0604, MN0801, MN1292]"
city,str,272,0,"[Manhattan, New York, New York City, STATEN ISLAND, BRONX]"
postal_code,str,379,0,"[10036, 10017, 10032, 10021, 10034]"
multifamily_housing_number_2,float64,396,25663,"[105.0, 20.0, 0.0, 251.0, 226.0]"
multifamily_housing_number_6,float64,421,12303,"[0.0, 15.0, 25.0, 13.0, 45.0]"
medical_office_number_of_2,float64,426,38046,"[11.53, 13.0, 340.0, 107.0, 30.0]"
parking_open_parking_lot,float64,446,35439,"[0.0, 79196.0, 91262.0, 5246.0, 198170.0]"
restaurant_worker_density,float64,508,37845,"[2.2011, 2.19984, 2.2, 2.20034, 0.14164]"
medical_office_number_of,float64,515,38046,"[10.48, 13.0, 350.0, 122.0, 35.0]"
office_weekly_operating_hours,float64,586,35034,"[65.0, 76.0, 98.0, 39.18, 66.18]"
electricity_weather_normalized_1,float64,682,9104,"[13.0, 8.6, 11.0, 12.1, 17.3]"
multifamily_housing_number_4,float64,754,12303,"[0.0, 105.0, 340.0, 921.0, 481.0]"
medical_office_gross_floor,float64,810,38046,"[5241.0, 5184.0, 107393.0, 42312.0, 11996.0]"
fuel_oil_4_use_kbtu,float64,848,38055,"[8103525.8, 5827298.1, 3212438.0, 6732994.7, 4323848.3]"
restaurant_gross_floor_area,float64,884,37829,"[3262.0, 18515.0, 34269.0, 6449.0, 10390.0]"
percent_electricity,float64,1002,9428,"[81.3, 33.7, 62.6, 49.8, 74.2]"
district_steam_use_kbtu,float64,1220,37624,"[6620658.4, 22263884.8, 11904586.2, 14319701.5, 7638053.8]"
ct2020,float64,1374,1354,"[119.0, 88.0, 125.0, 90.0, 116.0]"
direct_ghg_emissions_intensity,float64,1469,10036,"[0.04, 0.07, 0.24, 0.84, 15.83]"
k_12_school_gross_floor_area,float64,1529,36944,"[171725.0, 124900.0, 175325.0, 111600.0, 188575.0]"
annual_maximum_demand_kw,float64,1690,36450,"[2403.8, 278.9, 258.6, 291.2, 138.2]"
office_number_of_workers,float64,1703,35034,"[2268.78, 332.0, 344.08, 422.0, 893.0]"
indirect_location_based_ghg_1,float64,1729,8951,"[5.77, 7.25, 5.67, 7.16, 7.12]"
national_median_site_eui,float64,1743,940,"[46.6, 114.4, 89.3, 99.1, 91.0]"
office_number_of_computers,float64,1747,35034,"[3883.2, 1670.0, 299.2, 1810.0, 3008.0]"
multifamily_housing_total,float64,1812,12303,"[716.78, 105.0, 340.0, 921.0, 481.0]"
parking_completely_enclosed,float64,1952,35439,"[211980.0, 0.0, 84718.0, 141378.0, 68700.0]"
parent_property_id,str,2003,0,"[Not Applicable: Standalone Property, 28400, 28402, 48489992, 33999525]"
parent_property_name,str,2003,0,"[Not Applicable: Standalone Property, NYP Columbia (West Campus), NYP Cornell (East Campus), ABC Building, Brewster LLC (Parent)]"
parking_gross_floor_area,float64,2088,35439,"[211980.0, 0.0, 84718.0, 141378.0, 68700.0]"
retail_store_gross_floor,float64,2105,36289,"[4840.0, 23310.0, 6021.0, 61047.0, 12885.0]"
national_median_source_eui,float64,2248,940,"[116.4, 199.1, 196.3, 197.1, 214.5]"
total_location_based_ghg_1,float64,2315,8521,"[5.81, 7.25, 5.75, 7.41, 7.96]"
property_gfa_calculated_2,float64,2326,35439,"[211980.0, 79196.0, 91262.0, 84718.0, 141378.0]"
annual_maximum_demand_meter,str,2409,36450,"[Con Ed 494021425800009 (ELECTRIC) (5704952), 0200140E (8052689), 0200146E (8052691), 0200168E (8080069), 0200184E (8080071)]"
third_use_gfa_sqft,float64,2468,35453,"[9494.0, 16383.0, 32668.0, 6021.0, 61047.0]"
office_worker_density_number,float64,2704,35046,"[3.39333, 0.98462, 2.3, 1.20918, 0.87489]"
site_eui_kbtu_ft,float64,2713,8513,"[54.9, 87.6, 59.5, 82.4, 79.7]"
multifamily_housing_number,float64,2720,12303,"[836.24, 264.0, 600.0, 1700.0, 579.0]"
fuel_oil_2_use_kbtu,float64,3245,34261,"[8214759.8, 8033460.0, 1656000.0, 11065585.1, 483138.1]"
office_gross_floor_area_ft,float64,3347,35032,"[668602.0, 337187.0, 149601.0, 348996.0, 1020704.0]"
source_eui_kbtu_ft,float64,3885,8513,"[137.2, 152.4, 130.9, 163.9, 187.9]"
multifamily_housing_number_5,float64,4797,12313,"[0.0, 0.34386, 0.90498, 1.07861, 1.17459]"
second_use_gfa_sqft,float64,5434,29718,"[11116.0, 23310.0, 149601.0, 34269.0, 480712.0]"
property_notes,str,9460,26598,"[1-00997-0029, 1-01315-0001, 1-00999-0019, 1-01319-0047, 1-00995-0005]"
multifamily_housing_number_7,float64,11704,12313,"[0.0, 0.29101, 0.1909, 0.24649, 0.32459]"
water_use_all_water_sources,float64,13953,20470,"[5235.6, 18617.9, 259.3, 12545.7, 4842.2]"
multifamily_housing_gross,float64,17038,12301,"[595530.5, 305355.0, 375698.0, 853879.0, 409506.0]"
multifamily_housing_total_1,float64,17137,12313,"[1.20359, 0.34386, 0.90498, 1.07861, 1.17459]"
multifamily_housing_number_1,float64,17593,12313,"[1.4042, 0.86457, 1.59703, 1.99091, 1.4139]"
direct_ghg_emissions_metric,float64,20871,10024,"[26.36, 41.13, 94.18, 1324.9, 81430.71]"
indirect_location_based_ghg,float64,21231,8939,"[4005.61, 2777.92, 3231.54, 2788.78, 11265.36]"
property_gfa_self_reported,float64,24812,0,"[694052.0, 383165.0, 569516.0, 389286.0, 1581387.0]"
largest_use_gfa_sqft,float64,24846,44,"[668602.0, 337187.0, 368732.0, 348996.0, 1020704.0]"
total_location_based_ghg,float64,25468,8503,"[4031.96, 2777.92, 3272.67, 2882.96, 12590.26]"
natural_gas_use_kbtu,float64,26948,10201,"[496217.0, 774287.0, 1773133.0, 24944128.4, 1521640328.0]"
national_median_total_location,float64,27806,1005,"[3419.1, 3629.29, 4909.82, 3467.54, 14376.76]"
nyc_borough_block_and_lot,str,27921,219,"[1009970029, 1013150001, 1009990019, 1013190047, 1009950005]"
list_of_all_property_use,str,28910,26,"[Office (668602.0), Financial Office (11116.0), Food Service (9494.0), Bank Branch (0.0), Retail Store (4840.0), Restaurant (3262.0), Office (337187.0), Financial Office (16383.0), Bank Branch (3023.0), Retail Store (23310.0), Other - Entertainment/Public Assembly (32668.0), Restaurant (18515.0), Office (149601.0), Financial Office (368732.0), Restaurant (34269.0), Office (348996.0), Retail Store (6021.0), Office (1020704.0), Financial Office (480712.0), Food Service (18924.0), Retail Store (61047.0)]"
longitude,float64,29103,1354,"[-73.982826, -73.974306, -73.982504, -73.972753, -73.986244]"
electricity_use_grid_purchase,float64,29183,8928,"[30985171.8, 11292602.7, 21210798.2, 15970241.0, 93478416.6]"
latitude,float64,29742,1354,"[40.756631, 40.750698, 40.75831, 40.753074, 40.756181]"
site_energy_use_kbtu,float64,30048,8495,"[38102047.2, 33556487.5, 33889671.3, 32063075.4, 126060598.7]"
source_energy_use_kbtu,float64,30053,8495,"[95244433.0, 58403655.9, 74524942.6, 63805653.8, 297119793.8]"